# Name: Edward Tupacz

## Due 09/22 23:59

Please anwswer the following questions:

1.Implement matrix multiplication of two ${3} \times {3}$ **matrix** $A$ and $B$ using **vector multiplication**:

Given $A = \begin{bmatrix} 
a_1 \\
a_2 \\
a_3
\end{bmatrix}$
and 
$B = \begin{bmatrix} 
b_1 & b_2 & b_3 \\
\end{bmatrix}$
where $a_i \in {\mathbb{R}}^{1 \times 3}$ and $b_i \in {\mathbb{R}}^{3 \times 1}$ $(i=1,2,3)$

Recall how we solve the problem during the class, you can use np.dot(a_i, b_j) to evaluate the vector multiplications.

### Attention!!!
### If you use np.dot(A,B) (matrix multiplication of two matrix directly) as your submission in this question, you will get a 0 for homework5 and no resubmission will be accepted! 

Input: two ${3} \times {3}$ **matrix** : $A, B$

Output: Result of $AB$, a ${3} \times {3}$ **matrix**

In [1]:
import numpy as np
#Your Answer here
def my_MM(A, B):
    c00=A[0,0]*B[0,0]+A[0,1]*B[1,0]+A[0,2]*B[2,0]
    c01=A[0,0]*B[0,1]+A[0,1]*B[1,1]+A[0,2]*B[2,1]
    c02=A[0,0]*B[0,2]+A[0,1]*B[1,2]+A[0,2]*B[2,2]
    c10=A[1,0]*B[0,0]+A[1,1]*B[1,0]+A[1,2]*B[2,0]
    c11=A[1,0]*B[0,1]+A[1,1]*B[1,1]+A[1,2]*B[2,1]
    c12=A[1,0]*B[0,2]+A[1,1]*B[1,2]+A[1,2]*B[2,2]
    c20=A[2,0]*B[0,0]+A[2,1]*B[1,0]+A[2,2]*B[2,0]
    c21=A[2,0]*B[0,1]+A[2,1]*B[1,1]+A[2,2]*B[2,1]
    c22=A[2,0]*B[0,2]+A[2,1]*B[1,2]+A[2,2]*B[2,2]
    return np.array([[c00,c01,c02],[c10,c11,c12],[c20,c21,c22]])

2.Verify your implementation with numpy build in function np.dot with the example I give

You just need to run the cell below.

In [2]:
#Your Answer here
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[1,4,7],[2,5,8],[3,6,9]]
A = np.array(A)
B = np.array(B)
print(my_MM(A,B))
print(np.dot(A,B))

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
